### ISSUE TITLE
Question: Does this result in a double pass?

### ISSUE THREAD

**Issue by mumby0168** [hexarc-software/hexarc-serialization#1]
Hi, I have been looking at the code in the `UnionConverter` I was curious as I have been doing a similar thing with `Newtonsoft.Json` does the below result in a double pass of the JSON to deserialize it once into the `JsonDocument` then back into the actual type?

https://github.com/hexarc-software/hexarc-serialization/blob/5365dbb2ea0eff0f35701a17d2b016a924f4e068/Hexarc.Serialization.Union/UnionConverter.cs#L23

**Comment by shadeglare** [comment]
Hi, @mumby0168. Thanks for reaching me out.

Seems yes. My approach requires something like `Utf8JsonReader -> JsonDocument -> Object of T` conversion. And the last step may not have optimal performance as there are additional buffer read/write operations.

I just updated the library. Now it uses the .NET 6 built-in extension method to deserialize a `JsonDocument` object into a object of the requested type. So the performance must be improved.
